# Generated by Django 4.2.2 on 2025-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
