# Generated by Django 4.2.2 on 2025-06-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
