# Generated by Django 4.2.2 on 2025-06-28 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_employee_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsezid', models.CharField(max_length=50)),
                ('card_print_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_prints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-card_print_date'],
            },
        ),
    ]
