# Generated by Django 4.2.2 on 2025-06-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cardprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprint',
            name='card_print_date',
            field=models.DateField(),
        ),
    ]
