# Generated by Django 4.2.2 on 2025-06-28 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cardprint_card_print_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprint',
            name='card_print_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
